### PR TITLE
Multi instance capability

### PR DESCRIPTION
**Pull request by arturum1**
This PR could be merged in a new branch to prevent breaking current IOb-SoC implementation if using this version of UART.

It is based in including macro comments `/*<InstanceName>*/` inside pio.v, inst.v and inst_tb.v. 
These macros will be replaced by the build scripts with the correct peripheral instance name, therefore preventing errors due to duplicate definitions of modules.

### CODE REVIEW

**Comment by jjts** [comment]
please target branch multi-instance: thanks

**Comment by jjts** [comment]
request review from Pedro

**Comment by jjts** [comment]
already requested

**Review by P-Miranda — APPROVED** [review]
Changes seem good

**Pull request merged**
