### PR TITLE
Build-dir

### PR DESCRIPTION
**Pull request by JDLopes**
- update LIB submodule;
- remove .gitignore file;
- add vivado folder to avoid setup error.

### CODE REVIEW

**Comment by jjts** [comment]
Check fail. Pls fix.

**Comment by JDLopes** [comment]
> Check fail. Pls fix.

I run it on my PC and I have no problems. It passed the tests.

**Comment by JDLopes** [comment]
> Check fail. Pls fix.

Done!

**Review by jjts — COMMENTED** [review]
Not the way to fix this. If the repo has no fpga folder, the user does not want any fpga stuff. If there is only fpga/vivado, the user only wants to run vivado. Etc.

**Pull request closed without merging**
